name: Call Reusable Docker Release-Please Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: Jmainguy/docker-workflows/.github/workflows/docker-release.yml@v1
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      docker_url: zot.soh.re
      image_name: ${{ github.event.repository.name }}
